CREATE DATABASE registro;
SHOW DATABASE;
USE registro;
SHOW TABLES;
CREATE USER 'alfon'@'localhost' IDENTIFIED BY '1080';
GRANT ALL PRIVILEGES ON registro.* TO 'alfon'@'localhost';
FLUSH PRIVILEGES;
CREATE TABLE datos(id INT unsigned NOT NULL AUTO_INCREMENT, nombre VARCHAR(150) NOT NULL, password VARCHAR(150) NOT NULL, email VARCHAR(150) NOT NULL, fechareg DATE NOT NULL, PRIMARY KEY (id));
